### ISSUE TITLE
Nos envios dos emails, só fazer o return se o usuário existir.

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/sites#101]
```
$user = User::where('codpes',$this->site->owner)->first();
        return $this->view('emails.aprova_site')
...
                    ->cc([$user->email])
...
);
```

Deveria ser...

```
$user = User::where('codpes',$this->site->owner)->first();
if($user) {
        return $this->view('emails.aprova_site')
...
                    ->cc([$user->email])
...
}
);

**Comment by acesarfs** [comment]
O que deve retornar se o usuário não existir? Pelo que entendi, é preciso retornar uma view.

**Comment by thiagogomesverissimo** [comment]
não retona nada e dispara uma mensagem de flash dizendo que o email não foi enviado pq o usário não consta na base de dados

**Comment by acesarfs** [comment]
Se eu simplesmente retornar nada, aparece a mensagem "InvalidArgumentException
Invalid view."
Eu tento retornar null, por exemplo, que é quando não tem usuário, para fazer um if e exibir a mensagem flash, mas mesmo assim dá o mesmo erro. Nesse caso, faço uma outra view para os quando não tiver usuário?

**Comment by thiagogomesverissimo** [comment]
Então faz o seguinte:
QUando o usuário não existir, dispare o email para nós mesmo:

```
if(!$user){
...
cc(config('mail.reply_to.address'))
...
}
```

**Comment by acesarfs** [comment]
Talvez seja um pouco mais complicado porque tenho que verificar se, nos casos de atualização dos administradores e mudança de responsável, se eles existem pra mandar e-mail pra eles também..
