### ISSUE TITLE
Corrigir url do chamado que vai no email (exemplo: https://sites.fflch.usp.br//chamados/213/172) está com udas barras

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/sites#110]

**Comment by acesarfs** [comment]
Como já faz muito tempo e se não estou enganado, acho que já foi corrigido:

![image](https://user-images.githubusercontent.com/6999014/113757944-a386d100-96e9-11eb-900d-3f0d5f18300e.png)

**Comment by thiagogomesverissimo** [comment]
Eu corrigi =)
